repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      # - id: check-added-large-files
      #   args: [--maxkb=1000]

  # - repo: https://github.com/golangci/golangci-lint
  #   rev: v1.54.2
  #   hooks:
  #     - id: golangci-lint

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      # - id: go-vet
      # - id: go-imports
      # - id: go-cyclo
      # args: [-over=15]
      - id: validate-toml
      - id: no-go-testing
      - id: go-critic
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.0.3
  #   hooks:
  #     - id: prettier
  #       types_or: [javascript, jsx, ts, tsx, json]
  #       files: ^web/

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.49.0
  #   hooks:
  #     - id: eslint
  #       files: ^web/.*\.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx in web folder
  #       types: [file]
  #       additional_dependencies:
  #         - eslint@9.6.0
  #         - typescript@5.2.2
  #         - "@typescript-eslint/parser@6.7.0"
  #         - "@typescript-eslint/eslint-plugin@6.7.0"
